site_name: Card Game Documentation
site_url: https://Team43CardGame.github.io/Game/
docs_dir: docs
theme:
  name: material
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Readme: index.md
  - Documentation:
    - Development: CONTRIBUTING.md
    - Quality proof: 
      - Quality attribute scenarios: quality-attributes/quality-attribute-scenarios.md
      - Automated tests: quality-assurance/automated-tests.md
      - User acceptance tests: quality-assurance/user-acceptance-tests.md
    - Build and Deployment automation: 
      - Continuos Integration: automation/continuous-integration.md
      - Continuous Delivery: automation/continuous-delivery.md
    - Architecture:
      - Overview: architecture/architecture.md
    - Changelog: Changelog.md