name: Linting and Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Установка Unity через Docker (без активации)
    - name: Setup Unity
      run: |
        docker pull unityci/editor:ubuntu-6000.1.6f1-webgl
        docker tag unityci/editor:ubuntu-6000.1.6f1-webgl unity-editor

    # Линтинг
    - name: Run Super-Linter for C#
      uses: super-linter/super-linter@v7.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_WORKSPACE: ./Files/Scripts
        VALIDATE_CSHARP: true
        OUTPUT_FORMAT: sarif
        OUTPUT_DETAIL: detailed
        OUTPUT_SARIF: ./sarif-report.sarif
        FILTER_REGEX_EXCLUDE: .*\.meta$  # Исключаем meta-файлы
      continue-on-error: true

    # Запуск юнит-тестов через Unity Test Runner
    - name: Run Unity tests
      run: |
        docker run \
          -v "$(pwd):/project" \
          -w /project \
          unity-editor \
          unity-editor \
          -batchmode \
          -nographics \
          -quit \
          -logFile /dev/stdout \
          -projectPath /project \
          -runTests \
          -testPlatform EditMode \
          -testResults /project/test-results.xml

    # Публикация результатов
    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ./test-results.xml
          ./sarif-report.sarif

    - name: Upload SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ./sarif-report.sarif
      continue-on-error: true
