name: Linting and Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint and Run EditMode Tests
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Линтинг
      - name: Run Super-Linter for C#
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_WORKSPACE: ./Assets/Scripts
          VALIDATE_CSHARP: true
          FILTER_REGEX_EXCLUDE: .*\.meta$
        continue-on-error: true

      # Кэшируем папку Library
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Запускаем EditMode тесты
      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          unityVersion: 6000.1.6f1
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: EditMode Test Results

      # Отладка структуры artifacts (опционально)
      - name: Debug Artifacts Directory
        run: ls -la artifacts/ || echo "Artifacts directory not found"
        continue-on-error: true

      # Преобразуем результаты тестов в читаемый формат
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: EditMode Test Results
          path: artifacts/**/TestResults-*.xml
          reporter: java-junit
          fail-on-error: false

      # Загружаем результаты тестов как артефакт
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: artifacts
