name: Check
on: push
jobs:
  lint:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
    
