name: Check_Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
  
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VALIDATE_ALL_CODEBASE: true
